import os
import datetime
import logging
import uuid
import re
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.graphics.shapes import Drawing, Line

logger = logging.getLogger(__name__)

# Ensure the output directory exists automatically
PDF_DIR = "generated_pdfs"
os.makedirs(PDF_DIR, exist_ok=True)

# Register custom font (Nirmala UI) for Devanagari (Hindi) Support
try:
    font_path = os.path.join("app", "assets", "fonts", "Nirmala.ttf")
    pdfmetrics.registerFont(TTFont('Nirmala', font_path))
    DEFAULT_FONT = 'Nirmala'
except Exception as e:
    logger.warning(f"Failed to load Nirmala font for Hindi support: {e}. Falling back to Helvetica.")
    DEFAULT_FONT = 'Helvetica'

def header_footer(canvas, doc):
    """Draws the footer and page number on every page."""
    canvas.saveState()
    
    # Draw top header accent line
    canvas.setStrokeColor(colors.HexColor("#3B82F6")) # Blue accent
    canvas.setLineWidth(2)
    canvas.line(doc.leftMargin, doc.height + doc.topMargin + 10, doc.width + doc.leftMargin, doc.height + doc.topMargin + 10)
    
    # Draw Footer Line
    canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
    canvas.setLineWidth(1)
    canvas.line(doc.leftMargin, doc.bottomMargin - 20, doc.width + doc.leftMargin, doc.bottomMargin - 20)
    
    # Draw Page Number & Footer Text
    canvas.setFont(DEFAULT_FONT, 9)
    canvas.setFillColor(colors.gray)
    canvas.drawString(doc.leftMargin, doc.bottomMargin - 35, "AI PYQ Agent - Generative Output")
    
    page_num = canvas.getPageNumber()
    canvas.drawRightString(doc.width + doc.leftMargin, doc.bottomMargin - 35, f"Page {page_num}")
    canvas.restoreState()

def create_divider(width):
    """Creates an elegant visual divider line between questions."""
    d = Drawing(width, 10)
    d.add(Line(0, 5, width, 5, strokeColor=colors.HexColor("#CBD5E1"), strokeWidth=1))
    return d

def generate_content_pdf(title: str, content: str) -> str:
    """
    Generates a highly professional PDF containing the text content.
    """
    try:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        unique_id = str(uuid.uuid4())[:8]
        filename = f"export_{timestamp}_{unique_id}.pdf"
        file_path = os.path.join(PDF_DIR, filename)
        
        # 1. Initialize Document with Print-friendly standard margins
        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=60,
            leftMargin=60,
            topMargin=60,
            bottomMargin=70
        )
        
        styles = getSampleStyleSheet()
        
        # 2. Advanced Typography Setup
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Title'],
            fontName=DEFAULT_FONT,
            fontSize=26,
            textColor=colors.HexColor("#1E3A8A"), # Deep blue
            spaceAfter=25,
            alignment=1 # Center
        )
        
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontName=DEFAULT_FONT,
            fontSize=11,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=40,
            alignment=1
        )
        
        content_style = ParagraphStyle(
            'Content',
            parent=styles['Normal'],
            fontName=DEFAULT_FONT,
            fontSize=11,
            textColor=colors.HexColor("#1F2937"),
            spaceBefore=10,
            spaceAfter=15,
            leading=18 # Improved readability and line height
        )
        
        story = []
        
        # 3. Create Title Page
        story.append(Spacer(1, 150)) # Push title down gracefully
        story.append(Paragraph(title or "Previous Year Questions", title_style))
        
        generated_time = datetime.datetime.now().strftime("%B %d, %Y - %H:%M")
        story.append(Paragraph(f"Generated by AI PYQ Agent on {generated_time}", subtitle_style))
        story.append(PageBreak()) # Move actual content to the next page
        
        # 4. Parse Content & Handle Individual Questions
        # We split by the separator we defined in pyq_prompts.py (hyphens)
        blocks = re.split(r'-{30,}', content)
        
        for idx, block in enumerate(blocks):
            if not block.strip():
                continue
                
            block_content = block.strip().replace("\n", "<br/>")
            
            # Use KeepTogether so a question doesn't awkwardly split across two pages
            element = [
                Paragraph(block_content, content_style),
                Spacer(1, 10)
            ]
            
            # Add visual divider unless it's the last question
            if idx < len(blocks) - 1 and len(blocks) > 1:
                element.append(create_divider(doc.width))
                element.append(Spacer(1, 10))
                
            story.append(KeepTogether(element))
                
        # 5. Build PDF with Custom Header/Footer Engine
        doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
        logger.info(f"Successfully generated high-quality PDF at: {file_path}")
        return file_path
        
    except Exception as e:
        logger.error(f"Error generating PDF in service: {e}")
        raise e
